name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast1
  REPO_NAME: neatspace-backend
  SERVICE_NAME: neatspace-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Log in to Google Cloud using the key we added to Secrets
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Configure Docker to talk to Google Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 3. Build the Go App Container
      # We tag it with the specific commit SHA so we can track versions
      - name: Build and Push Container
        run: |
          docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

      # 4. Run Database Migrations
      - name: Run Database Migrations
        run: |
          docker run --rm \
            -e DATABASE_URL="${{ secrets.DB_URL }}" \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            migrate:up

      # 5. Deploy the Container to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
          # Important: Allowing unauthenticated invocations so you can test it easily
          # You can remove this line later for internal APIs
          flags: '--allow-unauthenticated'
          env_vars: |
            DATABASE_URL=${{ secrets.DB_URL }}

            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            APP_MODE=production
            LOG_LEVEL=info
            SERVER_HOST=0.0.0.0
            SERVER_PORT=8080

            CORS_CREDENTIALS=true
            SMTP_HOST=smtp.gmail.com
            SMTP_PORT=587
            SMTP_SECURE=false
            SMTP_SENDER_NAME=${{ secrets.SMTP_SENDER_NAME }}
            SMTP_SENDER_EMAIL=${{ secrets.SMTP_SENDER_EMAIL }}
            SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}